MathClubTracker/Controllers/CodeController.cs
using MathClubTracker.Domain.DomainTransferObjects;
using MathClubTracker.NHibernate.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MathClubTracker.Controllers
{
    public class CodeController : BaseController
    {
        //
        // GET: /Code/

        public JsonResult GraduationYear()
        {
            List<int> years = new List<int>();
            for (int i = 2017; i <= 2027;i++)
            {
                years.Add(i);
            }
            return Json(years, JsonRequestBehavior.AllowGet);
        }

        public JsonResult ClassSession()
        {
            ClassService svc = new ClassService(MySession);
            return Json(ClassDTO.GetClassDTOListFromClassList(svc.GetCurrentClasses().ToList()), JsonRequestBehavior.AllowGet);
        }

    }
}

MathClubTracker/Controllers/StudentController.cs
using MathClubTracker.Domain;
using MathClubTracker.Domain.DomainObjects;
using MathClubTracker.Domain.Search;
using MathClubTracker.NHibernate.Services;
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using Newtonsoft.Json;
using MathClubTracker.Domain.DomainTransferObjects;
using System.Web;
using System.IO;

namespace MathClubTracker.Controllers
{
    public class StudentController : BaseController

    {
        private StudentService _studentService;
        //
        // GET: /Student/
        public StudentController()
        {
            _studentService =  new StudentService(MySession);
        }

        public ActionResult Index()
        {

            StudentService studentService = new StudentService(MySession);
            List<Student> students = studentService.GetStudents();
            return View();
        }

        public ActionResult Detail(int id)
        {
            StudentDTO student = _studentService.GetById(id);
            return View(student);
        }

        public bool GetAttended(int sessionId = 0)
        {
            if (sessionId == 0)
            {
                return false;
            }
            
            return true;
        }

        //public IList<ClassSession> GetAllAttended(int id)
        //{
        //    StudentDTO student = _studentService.GetById(id);
        //    return null;
        //}

        [System.Web.Http.AcceptVerbs("GET", "POST")]
        public JsonResult GetAllStudents()
        {
            List<Student> students = _studentService.GetStudents();
            List<StudentDTO> dtos = BaseDomainObject.CopyList<StudentDTO, Student>(students);
            return Json(new { result = dtos, count = dtos.Count }, JsonRequestBehavior.AllowGet);
        }

        [System.Web.Http.AcceptVerbs("GET", "POST")]
        public JsonResult PagingGetStudents()
        {
            int skip = int.Parse(Request.QueryString["$skip"]);
            int top = int.Parse(Request.QueryString["$top"]);
            string orderby = Request.QueryString["$orderby"];
            int count = 0;
            List<Student> students = _studentService.GetStudents(skip, top, orderby, out count);
            List<StudentDTO> dtos = BaseDomainObject.CopyList<StudentDTO, Student>(students);
            return Json(new { result = dtos, count = count }, JsonRequestBehavior.AllowGet);
        }

        [System.Web.Http.AcceptVerbs("GET", "POST")]
        public JsonResult AddStudent(int? MathGeniusId, string LastName, string FirstName, string Sex, int? GraduationYear)
        {
            string sex = Sex == "Male" ? "M" : "F";
            ServiceResult result = _studentService.AddStudent(MathGeniusId, LastName, FirstName, sex , GraduationYear);
            return Json(FinalizeResult(result), JsonRequestBehavior.AllowGet);
        }

        public JsonResult UploadStudents()
        {
            ServiceResult result = new ServiceResult();
            foreach (string file in Request.Files)
            {
                MemoryStream target = new MemoryStream();
                Request.Files[file].InputStream.CopyTo(target);
                byte[] data = target.ToArray();
                string txt = System.Text.Encoding.UTF8.GetString(data);
                result.Merge(_studentService.ProcessUploadedStudentFile(txt));
            }
            return Json(FinalizeResult(result), JsonRequestBehavior.AllowGet);
        }

        [System.Web.Http.AcceptVerbs("GET", "POST")]
        public virtual JsonResult GetStudentDetails(int Id)
        {
            StudentDTO student = _studentService.GetStudent(Id);
            return Json(student, JsonRequestBehavior.AllowGet);
        }

        public JsonResult DeleteStudent(int Id)
        {
            ServiceResult result = new ServiceResult();
            result = _studentService.DeleteStudent(Id);
            return Json(FinalizeResult(result), JsonRequestBehavior.AllowGet);
        }


    }
}

MathClubTracker/Controllers/WebApi/StudentController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using System.Web.Http.ModelBinding;
using System.Web.Http.OData;
using System.Web.Http.OData.Query;
using System.Web.Http.OData.Routing;
using MathClubTracker.Domain.DomainObjects;
using Microsoft.Data.OData;
using MathClubTracker.NHibernate.Services;
using MathClubTracker.Domain.DomainTransferObjects;

namespace MathClubTracker.Controllers.WebApi
{

    public class StudentController : BaseODataController


    {
        private StudentService studentService;
        public StudentController()
        {
            studentService = new StudentService(MySession);
        }


        private static ODataValidationSettings _validationSettings = new ODataValidationSettings();

        // GET: odata/Student
        public IHttpActionResult GetStudent(ODataQueryOptions<Student> queryOptions)
        {
            // validate the query.
            try
            {
                queryOptions.Validate(_validationSettings);

                string filter = queryOptions.RawValues.Filter;
                int skip = 0;
                int top = 10;
                string orderby = queryOptions.OrderBy.RawValue;
                int count = 0;
                List<StudentDTO> studentList = StudentDTO.StudentsToDTO(studentService.GetStudents(filter, skip, top, orderby, out count));
                return Ok<IEnumerable<StudentDTO>>(studentList);
            }
            catch (ODataException ex)
            {
                return BadRequest(ex.Message);
            }

            
        }

        // GET: odata/Student(5)
        public IHttpActionResult GetStudent([FromODataUri] int key, ODataQueryOptions<Student> queryOptions)
        {
            // validate the query.
            try
            {
                queryOptions.Validate(_validationSettings);
            }
            catch (ODataException ex)
            {
                return BadRequest(ex.Message);
            }

            StudentDTO student = studentService.GetById(key);
            return Ok<StudentDTO>(student);

        }

        // PUT: odata/Student(5)
        public IHttpActionResult Put([FromODataUri] int key, Delta<Student> delta)
        {
            Validate(delta.GetEntity());

            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            // TODO: Get the entity here.

            // delta.Put(student);

            // TODO: Save the patched entity.

            // return Updated(student);
            return StatusCode(HttpStatusCode.NotImplemented);
        }

        // POST: odata/Student
        public IHttpActionResult Post(Student student)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            // TODO: Add create logic here.

            // return Created(student);
            return StatusCode(HttpStatusCode.NotImplemented);
        }

        // PATCH: odata/Student(5)
        [AcceptVerbs("PATCH", "MERGE")]
        public IHttpActionResult Patch([FromODataUri] int key, Delta<Student> delta)
        {
            Validate(delta.GetEntity());

            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            // TODO: Get the entity here.

            // delta.Patch(student);

            // TODO: Save the patched entity.

            // return Updated(student);
            return StatusCode(HttpStatusCode.NotImplemented);
        }

        // DELETE: odata/Student(5)
        public IHttpActionResult Delete([FromODataUri] int key)
        {
            // TODO: Add delete logic here.

            // return StatusCode(HttpStatusCode.NoContent);
            return StatusCode(HttpStatusCode.NotImplemented);
        }
    }
}

MathClubTracker/Views/Student/Detail.cshtml
@model MathClubTracker.Domain.DomainTransferObjects.StudentDTO
@{
    ViewBag.Title = "Detail";
}

<h2>Student Detail</h2>

<table>
    <tr>
        <td><label>Name</label></td>
        <td>@Model.FirstName @Model.LastName</td>
    </tr>
    <tr><td><label>Graduation Year</label></td><td>@Model.GraduationYear</td></tr>
    <tr><td><label>Current Courses</label></td><td>XXX</td></tr>
</table>

<a href="@Url.Action("Index")">Back to Student Maintenance</a>
<a href="@Url.Action("Index", "Home")">Back to Main</a>

MathClubTracker/Views/Student/Index.cshtml
@{
    ViewBag.Title = "Student Maintenance";
}

<label>Student Maintenance Screen</label><br/><br/>




<div class="content-container-fluid">
    <div class="row">
        <table><tr><td><label>View Student : </label></td><td><input id="autoStudent" /></td><td><input type="button" value="GO" id="btnEditAuto" onclick="editFromAuto();" /></td></tr></table>
        <br/><br/>
    </div>

    <div class="row">
        <label>Add Student</label>
    </div>
    <div class="row">
        <table>
            <tr>
                <td>Math Genius Id</td>
                <td>Last Name</td>
                <td>First Name</td>
                <td>Sex</td>
                <td>Graduation Year</td>
                <td>&nbsp;</td>
            </tr>
            <tr>
                <td><input type="text" id="txtMathGeniusId" /></td>
                <td><input type="text" id="txtLastName" /></td>
                <td><input type="text" id="txtFirstName" /></td>
                <td>
                    <input type="text" id="sex" />
                    <div id="sexList">
                        <ul>
                            <li>Male</li>
                            <li>Female</li>
                        </ul>

                    </div>
                </td>
                <td><input type="text" id="gradyear" /></td>
                <td><input type="button" id="btnAddStudent" value="Add" ; onclick="AddStudent()" /></td>
            </tr>
        </table>
    </div>

    <div class="row">
        <label>Current Students</label>
        <br/>
    </div>
    <div class="row">
        <div class="cols-sample-area" style="width:600px">

            <div id="Grid" class="waiting"></div>
        </div>
    </div>
</div>


@* Student Grid Template *@
<script type="text/x-jsrender" id="mgTemplate">

    <a href="@Url.Action("Detail","Student")?id={{:Id}}">View</a>
    <a href="javascript:editStudent({{:Id}});">Edit</a>
    <a href="javascript:deleteStudent({{:Id}});">Delete</a>
</script>

<div class="content-container-fluid" id="deleteContainer" style="visibility:hidden" >
    <div class="row">
        <div class="cols-sample-area">
            <div class="control">
                <div id="deleteForm" title="Remove Math Genius Student">
                    <form id="form1">
                        <input type="hidden" id="deleteId" />
                        <table>
                            <tr>
                                <td>
                                    Do you wish to remove <label id="deleteName"></label> from the roster?
                                </td>
                            </tr>
                            <tr>
                                <td align="center">
                                    <br />
                                    <input type="button" id="btnDelete" value="Remove" class="e-btn" onclick="processDelete();" />
                                    <input type="button" id="btnCancel" value="Cancel" class="e-btn" onclick="deleteDialog.close();" />
                                    <label class="error" for="btn" generated="false"></label>
                                </td>
                            </tr>

                        </table>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>



    <script type="text/javascript">

        var deleteDialog;

        $(function () {
            $("#deleteForm").ejDialog(
                {
                    enableModal: true,
                    enableResize: false,
                    width: 400,
                    close: "onDialogClose",
                    containment: ".cols-sample-area",
                    showOnInit : false
                });

            deleteDialog = $("#deleteForm").data("ejDialog");

            $("#Grid").ejGrid({
                dataSource: ej.DataManager({ url: "@Url.Action("PagingGetStudents","Student")" }),
                allowPaging: true,
                pageSettings: { pageSize: 10, enableQueryString: true },
                allowSorting: true,
                allowMultiSorting: true,
                columns: [
                        { field: "Id", headerText: "Action", template: true, templateID: "#mgTemplate", width: 125, textAlign: ej.TextAlign.Left, },
                        { field: "MathGeniusId", headerText: "MG ID", width: 75, textAlign: ej.TextAlign.Center, },
                        { field: "LastName", headerText: "Last Name", width: 100, textAlign: ej.TextAlign.Left },
                        { field: "FirstName", headerText: "First Name", width: 100, textAlign: ej.TextAlign.Left },
                        { field: "Gender", headerText: "Sex", width: 75, textAlign: ej.TextAlign.Center },
                        { field: "GraduationYear", headerText: "Class Of", width: 125, textAlign: ej.TextAlign.Center }
                ]
            });

            var dataManger = ej.DataManager({
                url: "../oData"
            });
            // Query creation
            var query = ej.Query().from("Student").select("Id", "Name");
            $('#autoStudent').ejAutocomplete({
                dataSource: dataManger,
                query: query,
                fields: { text: "Name", key: "Id" },
                filterType: ej.filterType.StartsWith,
                watermarkText: "Search for students",
                width: 200
            });

            $("#txtMathGeniusId").ejNumericTextbox(
                         {
                             name: "numeric",
                             value: 100,
                             minValue: 1,
                             width: "100%"
                         });
            $('#sex').ejDropDownList({
                targetID: "sexList",
                watermarkText: "Sex",
                width: "100%"
            });

            $('#gradyear').ejDropDownList({
                dataSource: ej.DataManager({url: "@Url.Action("GraduationYear","Code")"   }),
            watermarkText: "Select a Graduation Year",
            width: "100%"
            });



            @*
            saveUrl = "@Url.Action("UploadStudents","Student")";
            removeUrl = "@Url.Action("RemoveFile","Student")";
            $("#UploadDefault").ejUploadbox({
                saveUrl: saveUrl,
                removeUrl: removeUrl,
                multipleFilesSelection: false,
                error: function (args) {
                    alert(args.error);
                }
            });*@

        });

        function AddStudent() {
            $("#btnAddStudent").prop("disabled", "disabled");
            $("#updateMessage").hide();
            $.ajax({
                url: '@Url.Action("AddStudent","Student")',
                data: {
                    MathGeniusId: $("#txtMathGeniusId").val(),
                    LastName: $("#txtLastName").val(),
                    FirstName: $("#txtFirstName").val(),
                    Sex: $("#sex").val(),
                    GraduationYear: $("#gradyear").val()
                },
                error: function (e) {
                    $("#updateMessage").show();
                    $('#updateMessage').html('<p>' + e + '</p>');
                },
                complete: function () {
                    $("#btnAddStudent").prop("disabled", "");
                },
                success: function (data) {
                    ProcessServiceResult(data, "#updateMessage", resetGrid(), null);
                },
                type: 'GET'
            });
        }

        function AddStudents() {

        }

        function resetGrid() {
            $("#Grid").ejGrid("refreshContent");
        }

        function deleteStudent(id) {
            $.ajax({
                url: '@Url.Action("GetStudentDetails", "Student")',
                data: {
                    Id: id
                },
                context: document.body,
                method: "POST",
                dataType: "json",
                success: function (data) {
                    $("#deleteName").text(data.Name);
                    $("#deleteId").val(data.Id);
                    $("#deleteContainer").css("visibility", "visible");
                    deleteDialog.open();
                },
                error: function (data) {
                    updateStatus("Error", data.responseText, true);
                }
            });
        }

        function editStudent(id) {
            alert('Edit ' + id);
        }

        function editFromAuto(id) {
            if ($("#autoStudent").ejAutocomplete("getSelectedItems").length > 0) {
                window.location = "@Url.Action("Detail","Student")?id=" + $("#autoStudent").ejAutocomplete("getSelectedItems")[0][0].Id;
            }
        }

        function processDelete() {
            $.ajax({
                url: '@Url.Action("DeleteStudent", "Student")',
                data: {
                    Id: $("#deleteId").val()
                },
                context: document.body,
                method: "POST",
                dataType: "json",
                success: function (data) {
                    deleteDialog.close();
                    ProcessServiceResult(data, "#updateMessage", resetGrid(), null);
                },
                error: function (data) {
                    updateStatus("Error", data.responseText, true);
                }
            });
        }

    </script>