MathClubWebApi/Areas/HelpPage/Models/HelpPageApiModel.cs
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Net.Http.Headers;
using System.Web.Http.Description;

namespace MathClubWebApi.Areas.HelpPage.Models
{
    /// <summary>
    /// The model that represents an API displayed on the help page.
    /// </summary>
    public class HelpPageApiModel
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="HelpPageApiModel"/> class.
        /// </summary>
        public HelpPageApiModel()
        {
            SampleRequests = new Dictionary<MediaTypeHeaderValue, object>();
            SampleResponses = new Dictionary<MediaTypeHeaderValue, object>();
            ErrorMessages = new Collection<string>();
        }

        /// <summary>
        /// Gets or sets the <see cref="ApiDescription"/> that describes the API.
        /// </summary>
        public ApiDescription ApiDescription { get; set; }

        /// <summary>
        /// Gets the sample requests associated with the API.
        /// </summary>
        public IDictionary<MediaTypeHeaderValue, object> SampleRequests { get; private set; }

        /// <summary>
        /// Gets the sample responses associated with the API.
        /// </summary>
        public IDictionary<MediaTypeHeaderValue, object> SampleResponses { get; private set; }

        /// <summary>
        /// Gets the error messages associated with this model.
        /// </summary>
        public Collection<string> ErrorMessages { get; private set; }
    }
}

MathClubWebApi/Areas/HelpPage/Controllers/HelpController.cs
using System;
using System.Web.Http;
using System.Web.Mvc;
using MathClubWebApi.Areas.HelpPage.Models;

namespace MathClubWebApi.Areas.HelpPage.Controllers
{
    /// <summary>
    /// The controller that will handle requests for the help page.
    /// </summary>
    public class HelpController : Controller
    {
        public HelpController()
            : this(GlobalConfiguration.Configuration)
        {
        }

        public HelpController(HttpConfiguration config)
        {
            Configuration = config;
        }

        public HttpConfiguration Configuration { get; private set; }

        public ActionResult Index()
        {
            return View(Configuration.Services.GetApiExplorer().ApiDescriptions);
        }

        public ActionResult Api(string apiId)
        {
            if (!String.IsNullOrEmpty(apiId))
            {
                HelpPageApiModel apiModel = Configuration.GetHelpPageApiModel(apiId);
                if (apiModel != null)
                {
                    return View(apiModel);
                }
            }

            return View("Error");
        }
    }
}

MathClubWebApi/Controllers/BaseApiController.cs
using MathClubTracker.NHibernate;
using NHibernate;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Http;
using System.Web.Mvc;

namespace MathClubWebApi.Controllers
{
    public class BaseApiController : ApiController
    {
        private NHibernateUnitOfWork MyUnitOfWork { get; set; }
        protected ISession MySession { get; set; }

        public BaseApiController()
        {
            MyUnitOfWork = (NHibernateUnitOfWork)MathClubWebApi.WebApiApplication.UnitOfWork;
            MySession = MyUnitOfWork.Session;


        }

    }
}

MathClubWebApi/Controllers/BaseController.cs
using MathClubTracker.NHibernate;
using NHibernate;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Http;
using System.Web.Mvc;

namespace MathClubWebApi.Controllers
{
    public class BaseController : ApiController
    {
        private NHibernateUnitOfWork MyUnitOfWork { get; set; }
        protected ISession MySession { get; set; }

        public BaseController()
        {
            MyUnitOfWork = (NHibernateUnitOfWork)MathClubWebApi.WebApiApplication.UnitOfWork;
            MySession = MyUnitOfWork.Session;


        }

    }
}

MathClubWebApi/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MathClubWebApi.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

MathClubWebApi/Controllers/StudentController.cs
using MathClubTracker.Domain;
using MathClubTracker.Domain.Models;
using MathClubTracker.NHibernate.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web;
using System.Web.Http;
using System.Web.Mvc;

namespace MathClubWebApi.Controllers
{
    public class StudentController : BaseController
    {
        //
        // GET: /Student/




        public IEnumerable<Student> GetAllStudents()
        {

            StudentService studentService = new StudentService(MySession);
            List<Student> students = studentService.GetStudents();
            return students;
        }

        public Student GetStudentById(int id)
        {
            StudentService studentService = new StudentService(MySession);

            Student student = studentService.GetById(id);
            if (student == null)
            {
                throw new HttpResponseException(HttpStatusCode.NotFound);
            }
            return student;
        }

        public HttpResponseMessage PostStudent(Student student)
        {
            StudentService studentService = new StudentService(MySession);
            studentService.InsertStudent(student);
            var response = Request.CreateResponse<Student>(HttpStatusCode.Created, student);

            string uri = Url.Link("DefaultApi", new { id = student.Id });
            response.Headers.Location = new Uri(uri);
            return response;
        }

        public void PutStudent(int id, StudentModel studentModel)
        {
            StudentService studentService = new StudentService(MySession);
            Student student = studentService.GetById(id);
            if (!studentService.UpdateStudent(student, studentModel))
            {
                throw new HttpResponseException(HttpStatusCode.NotFound);
            }
        }

        public void DeleteStudent(int id)
        {
            StudentService studentService = new StudentService(MySession);
            studentService.DeleteStudent(id);
        }

    }
}

MathClubWebApi/Controllers/ValuesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;

namespace MathClubWebApi.Controllers
{
    public class ValuesController : ApiController
    {
        // GET api/values
        public IEnumerable<string> Get()
        {
            return new string[] { "value1", "value2" };
        }

        // GET api/values/5
        public string Get(int id)
        {
            return "value";
        }

        // POST api/values
        public void Post([FromBody]string value)
        {
        }

        // PUT api/values/5
        public void Put(int id, [FromBody]string value)
        {
        }

        // DELETE api/values/5
        public void Delete(int id)
        {
        }
    }
}

MathClubWebApi/Views/Home/Index.cshtml
<div id="body">
    <section class="content-wrapper main-content clear-fix">
        <div>
            <h2>All Students</h2>
            <ul id="student" />
        </div>
        <div>
            <h2>Search by ID</h2>
            <input type="text" id="studentId" size="5" />
            <input type="button" value="Search" onclick="find();" />
            <p id="student" />
        </div>
    </section>
</div>

@section scripts {
<script>
    var apiUrl = 'api/student';

    $(document).ready(function () {
        // Send an AJAX request
        $.getJSON(apiUrl)
            .done(function (data) {
                // On success, 'data' contains a list of products.
                $.each(data, function (key, item) {
                    // Add a list item for the product.
                    $('<li>', { text: formatItem(item) }).appendTo($('#student'));
                });
            });
    });

    function formatItem(item) {
        return item.FirstName + ' ' + item.LastName;
    }

    function find() {
        var id = $('#studentId').val();
        $.getJSON(apiUrl + '/' + id)
            .done(function (data) {
                $('#student').text(formatItem(data));
            })
            .fail(function (jqXHR, textStatus, err) {
                $('#student').text('Error: ' + err);
            });
    }
</script>
}

MathClubWebApi/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <header>
        <div class="content-wrapper">
            <div class="float-left">
                <p class="site-title">
                    <a href="~/">ASP.NET Web API</a></p>
            </div>
            <div class="float-right">
                <nav>
                    <ul id="menu">
                        <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, null)</li>
                        <li>@Html.ActionLink("API", "Index", "Help", new { area = "" }, null)</li>
                    </ul>
                </nav>
            </div>
        </div>
    </header>
    @RenderBody()

    @Scripts.Render("~/bundles/jquery")
    @RenderSection("scripts", required: false)
</body>
</html>