MathClubTracker/Controllers/AssessmentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MathClubTracker.Controllers
{
    public class AssessmentController : Controller
    {
        // GET: Assessment
        public ActionResult Index()
        {
            return View();
        }
    }
}

MathClubTracker/Controllers/HomeController.cs
using MathClubTracker.Domain;
using MathClubTracker.Domain.DomainObjects;
using MathClubTracker.Domain.Search;
using MathClubTracker.NHibernate;
using MathClubTracker.NHibernate.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MathClubTracker.Controllers
{
    public class HomeController : BaseController
    {
        public ActionResult Index()
        {

            StudentService studentService = new StudentService(MySession);
            List<Student> students = studentService.GetStudents();
            

            ViewBag.Message = "Modify this template to jump-start your ASP.NET MVC application.";

            return View();
        }

        public ActionResult Scroller()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your app description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        //public ActionResult Students(string term)
        //{
        //    StudentService studentService = new StudentService(MySession);
        //    List<CodeValue> codeValueList = new List<CodeValue>();

        //    StudentSearchCriteria criteria = new StudentSearchCriteria();
        //    criteria.PartialName = term;
        //    List<Student> students = studentService.SearchStudents(criteria);

        //    List<StudentM> studentModels = MyModelFactory.CreateStudentList(students);
        //    return Json(studentModels);
        //}
    }

    public class CodeValue {

        public string item;
        public string value;
        public CodeValue(string _item, string _value) {
            item = _item;
            value = _value;

        }
    }
}

MathClubTracker/Controllers/StudentController.cs
using MathClubTracker.Domain;
using MathClubTracker.Domain.DomainObjects;
using MathClubTracker.Domain.Search;
using MathClubTracker.NHibernate.Services;
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using Newtonsoft.Json;
using MathClubTracker.Domain.DomainTransferObjects;
using System.Web;
using System.IO;

namespace MathClubTracker.Controllers
{
    public class StudentController : BaseController

    {
        private StudentService _studentService;
        //
        // GET: /Student/
        public StudentController()
        {
            _studentService =  new StudentService(MySession);
        }

        public ActionResult Index()
        {

            StudentService studentService = new StudentService(MySession);
            List<Student> students = studentService.GetStudents();
            return View();
        }

        public ActionResult Detail(int id)
        {
            StudentDTO student = _studentService.GetById(id);
            return View(student);
        }

        public bool GetAttended(int sessionId = 0)
        {
            if (sessionId == 0)
            {
                return false;
            }
            
            return true;
        }

        //public IList<ClassSession> GetAllAttended(int id)
        //{
        //    StudentDTO student = _studentService.GetById(id);
        //    return null;
        //}

        [System.Web.Http.AcceptVerbs("GET", "POST")]
        public JsonResult GetAllStudents()
        {
            List<Student> students = _studentService.GetStudents();
            List<StudentDTO> dtos = BaseDomainObject.CopyList<StudentDTO, Student>(students);
            return Json(new { result = dtos, count = dtos.Count }, JsonRequestBehavior.AllowGet);
        }

        [System.Web.Http.AcceptVerbs("GET", "POST")]
        public JsonResult PagingGetStudents()
        {
            int skip = int.Parse(Request.QueryString["$skip"]);
            int top = int.Parse(Request.QueryString["$top"]);
            string orderby = Request.QueryString["$orderby"];
            int count = 0;
            List<Student> students = _studentService.GetStudents(skip, top, orderby, out count);
            List<StudentDTO> dtos = BaseDomainObject.CopyList<StudentDTO, Student>(students);
            return Json(new { result = dtos, count = count }, JsonRequestBehavior.AllowGet);
        }

        [System.Web.Http.AcceptVerbs("GET", "POST")]
        public JsonResult AddStudent(int? MathGeniusId, string LastName, string FirstName, string Sex, int? GraduationYear)
        {
            string sex = Sex == "Male" ? "M" : "F";
            ServiceResult result = _studentService.AddStudent(MathGeniusId, LastName, FirstName, sex , GraduationYear);
            return Json(FinalizeResult(result), JsonRequestBehavior.AllowGet);
        }

        public JsonResult UploadStudents()
        {
            ServiceResult result = new ServiceResult();
            foreach (string file in Request.Files)
            {
                MemoryStream target = new MemoryStream();
                Request.Files[file].InputStream.CopyTo(target);
                byte[] data = target.ToArray();
                string txt = System.Text.Encoding.UTF8.GetString(data);
                result.Merge(_studentService.ProcessUploadedStudentFile(txt));
            }
            return Json(FinalizeResult(result), JsonRequestBehavior.AllowGet);
        }

        [System.Web.Http.AcceptVerbs("GET", "POST")]
        public virtual JsonResult GetStudentDetails(int Id)
        {
            StudentDTO student = _studentService.GetStudent(Id);
            return Json(student, JsonRequestBehavior.AllowGet);
        }

        public JsonResult DeleteStudent(int Id)
        {
            ServiceResult result = new ServiceResult();
            result = _studentService.DeleteStudent(Id);
            return Json(FinalizeResult(result), JsonRequestBehavior.AllowGet);
        }


    }
}

MathClubTracker/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}

<hgroup class="title">
    <h1>@ViewBag.Title.</h1>
    <h2>@ViewBag.Message</h2>
</hgroup>

<article>
    <p>
        Use this area to provide additional information.
    </p>

    <p>
        Use this area to provide additional information.
    </p>

    <p>
        Use this area to provide additional information.
    </p>
</article>

<aside>
    <h3>Aside Title</h3>
    <p>
        Use this area to provide additional information.
    </p>
    <ul>
        <li>@Html.ActionLink("Home", "Index", "Home")</li>
        <li>@Html.ActionLink("About", "About", "Home")</li>
        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
    </ul>
</aside>

MathClubTracker/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}

<hgroup class="title">
    <h1>@ViewBag.Title.</h1>
    <h2>@ViewBag.Message</h2>
</hgroup>

<section class="contact">
    <header>
        <h3>Phone</h3>
    </header>
    <p>
        <span class="label">Main:</span>
        <span>425.555.0100</span>
    </p>
    <p>
        <span class="label">After Hours:</span>
        <span>425.555.0199</span>
    </p>
</section>

<section class="contact">
    <header>
        <h3>Email</h3>
    </header>
    <p>
        <span class="label">Support:</span>
        <span><a href="mailto:Support@example.com">Support@example.com</a></span>
    </p>
    <p>
        <span class="label">Marketing:</span>
        <span><a href="mailto:Marketing@example.com">Marketing@example.com</a></span>
    </p>
    <p>
        <span class="label">General:</span>
        <span><a href="mailto:General@example.com">General@example.com</a></span>
    </p>
</section>

<section class="contact">
    <header>
        <h3>Address</h3>
    </header>
    <p>
        One Microsoft Way<br />
        Redmond, WA 98052-6399
    </p>
</section>

MathClubTracker/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}



<div class="content-container-fluid">
<div class="row">
    <a href="@Url.Action("Index","Student")">Student Maintenance</a>

</div>
    <div class="row">
        <a href="@Url.Action("Index","Assessment")">Test Maintenance</a>
    </div>
    <div class="row">
        1. Add Student<br/>
        2. Remove Student<br/>
        3. Edit Student<br/>
        4. Add Class<br/>
        5. Remove Class<br/>
        6. Edit Class<br/>
        7. Add Class Session<br/>
        8. Remove Class Session<br/>
        9. Edit Class Session<br/>
        9a. Add Students
        9b. Remove Students<br/>
        10. Add Course Category<br/>
        11. Remove Course Category<br/>
        12. Edit Course Category<br/>
        13. Browse Course Categories<br/>
        14. Load Scanned Test<br/>
        15. Edit Scanned Test<br/>
        16. Delete Scanned Test<br/>
        17. Display Test Results<br/>
    </div>


</div>

<div class="content-container-fluid">
    <div class="row">
        <div class="cols-sample-area">
            <div class="frame">
                <div class="control">
                    <div class="posupload">Select a file to upload </div>
                    <div id="UploadDefault"></div>
                </div>
            </div>
        </div>
    </div>
</div>

<style type="text/css">
    #UploadDefault {
        margin: 0 auto;
        padding: 10px;
    }

    .posupload {
        text-align: center;
    }
</style>


    <script type="text/javascript">



        $(function () {
            //debugger;



            saveUrl = "@Url.Action("UploadStudents","Student")";
            removeUrl = "@Url.Action("RemoveFile","Student")";
            $("#UploadDefault").ejUploadbox({
                saveUrl: saveUrl,
                removeUrl: removeUrl,
                multipleFilesSelection: false,
                error: function (args) {
                    alert(args.error);
                }
            });




        });




</script>

MathClubTracker/Views/Home/Scroller.cshtml
@{
    ViewBag.Title = "Scroller";
}
<h2>Scroller</h2>
<div id="scrollerButtons">
    <div class="conditionbutton" style="float:left; width:80px; background-color:#ccccff" id="btnCarrots" anchor="#carrots">Carrots</div>
    <div class="conditionbutton" style="float:left; width:80px; background-color:#ffcccc" id="btnPotatoes" anchor="#potatoes">Potatoes</div>
    <div class="conditionbutton" style="float:left; width:80px; background-color:#ccffcc" id="btnPeas" anchor="#peas">Peas</div>
    <div class="conditionbutton" style="float: left; width: 80px; background-color: #ffcc66" id="btnApples" anchor="#apples">Apples</div>
    <div class="conditionbutton" style="float: left; width: 80px; background-color: #ffcc99" id="btnOranges" anchor="#oranges">Oranges</div>
    <div class="conditionbutton" style="float: left; width: 80px; background-color: #ffff99" id="btnLemons" anchor="#lemons">Lemons</div>
</div>
<br/>
<div id="conditions">
    <div style="background-color:#ffcccc" id="potatoes">
        Potatoes
        <div style="margin-left:20px">This is the div for potatoes</div>
    </div>
    <div class="boundary"></div>
    <div style="background-color:#ccccff" id="carrots">
        Carrots
        <div>This is the div for carrots</div>
    </div>
    <div class="boundary"></div>
    <div style="background-color:#ccffcc" id="peas">
        Peas
        <div>This is the div for peas</div>
    </div>
    <div class="boundary"></div>
    <div style="background-color:#ffcc66" id="apples">
        Apples
        <div style="margin-left:20px">This is the div for apples</div>
    </div>
    <div class="boundary"></div>
    <div style="background-color:#ffcc99" id="oranges">
        Oranges
        <div>This is the div for oranges</div>
    </div>
    <div class="boundary"></div>
    <div style="background-color:#ffff99" id="lemons">
        Lemons
        <div>This is the div for lemons</div>
    </div>
</div>

<br/>

<table>
    <tbody data-bind="foreach: conditions">
        <tr>
            <td><div class="conditionbutton" style="float: left; width: 80px;" data-bind=" text:conditionName, id:conditionName, style: {'background-color': displayColor}, attr: {  'anchor': anchor }"></div>
</td>
        </tr>
    </tbody>
</table>

<div>
<table>
    <tr>
        <td>
            <div id='chartContainer' style="width:600px; height: 400px" />
        </td>
    </tr>
    <tr>
        <td>
            <div id='eventText' style="width:600px; height: 30px" />
        </td>
    </tr>
</table>
</div>



<script type="text/javascript">

    $(document).ready(function () {
        $("#conditions").jqxPanel({ width: 550, height: 450 });

        $(".conditionbutton").on('click', function () {
            $('#conditions').jqxPanel('scrollTo', 0, $(this.attributes["anchor"].nodeValue).position().top);
        });

        // prepare chart data
        var sampleData = [
                { Day: 'Monday', Keith: 30, Erica: 15, George: 25 },
                { Day: 'Tuesday', Keith: 25, Erica: 25, George: 30 },
                { Day: 'Wednesday', Keith: 30, Erica: 20, George: 25 },
                { Day: 'Thursday', Keith: 35, Erica: 25, George: 45 },
                { Day: 'Friday', Keith: 20, Erica: 20, George: 25 },
                { Day: 'Saturday', Keith: 30, Erica: 20, George: 30 },
                { Day: 'Sunday', Keith: 60, Erica: 45, George: 90 }
        ];

        // prepare jqxChart settings
        var settings = {
            title: "Fitness & exercise weekly scorecard",
            description: "Time spent in vigorous exercise",
            padding: { left: 5, top: 5, right: 5, bottom: 5 },
            titlePadding: { left: 90, top: 0, right: 0, bottom: 10 },
            source: sampleData,
            categoryAxis:
                {
                    dataField: 'Day',
                    showGridLines: false
                },
            colorScheme: 'scheme04',
            showToolTips: false,
            enableAnimations: true,
            seriesGroups:
                [
                    {
                        type: 'line',
                        valueAxis:
                        {
                            minValue: 0,
                            maxValue: 100,
                            unitInterval: 10,
                            description: 'Time in minutes'
                        },
                        mouseover: myEventHandler,
                        mouseout: myEventHandler,
                        click: myEventHandler,

                        series: [
                                { dataField: 'Keith', displayText: 'Keith' },
                                { dataField: 'Erica', displayText: 'Erica' },
                                { dataField: 'George', displayText: 'George' }
                        ]
                    }
                ]
        };

        function myEventHandler(e) {
            var eventData = '<div><b>Last Event: </b>' + e.event + '<b>, DataField: </b>' + e.serie.dataField + '<b>, Value: </b>' + e.elementValue + "</div>";
            $('#eventText').html(eventData);
        };

        // select the chartContainer DIV element and render the chart.
        $('#chartContainer').jqxChart(settings);

        function AppViewModel() {
            self.conditions = [
                    { anchor : '#oranges', conditionName: 'Keith', displayColor: '#cccfff' },
                    { anchor: '#apples', conditionName: 'Erica', displayColor: '#ccccff' },
                    { anchor: '#lemons', conditionName: 'George', displayColor: '#cccccf' }
            ]
        }

        // Activates knockout.js
        ko.applyBindings(new AppViewModel());




    });

</script>